"use strict";
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const state={projects:[],publications:[],experience:[],education:[],home:{},filter:"All",chatHistory:[],chatBusy:false};
async function json(file){const r=await fetch(`data/${file}.json`);if(!r.ok)throw new Error(`Could not load ${file}`);return r.json()}
function byOrder(items){return [...items].sort((a,b)=>(Number(a.sortOrder)||999)-(Number(b.sortOrder)||999)||(Number(b.priority)||0)-(Number(a.priority)||0)||String(b.date||b.issueDate||"").localeCompare(String(a.date||a.issueDate||"")))}
function dateLabel(value){if(!value)return "";const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.valueOf())?value:d.toLocaleDateString("en-US",{month:"short",year:"numeric"})}
function tags(items=[]){return `<div class="tags">${items.map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div>`}
function links(items=[]){return items.filter(x=>x.url).map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noreferrer">${esc(x.label)} ↗</a>`).join("")}
const pageFor={projects:"projects",publications:"research",experience:"experience",education:"education",licences:"credentials",cv:"cv",contact:"contact"};
const newsCategories=new Set(Object.keys(pageFor));
function renderNews(items){$("#newsList").innerHTML=[...items].filter(x=>newsCategories.has(x.category)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,10).map((x,i)=>`<li class="news-item"><span class="news-number">${String(i+1).padStart(2,"0")}</span><div><div class="news-meta"><span>${esc(x.category)}</span><time datetime="${esc(x.createdAt)}">${esc(new Date(x.createdAt).toLocaleDateString("en-US",{day:"numeric",month:"short",year:"numeric"}))}</time></div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><a href="#${pageFor[x.category]}" data-focus="${esc(x.sourceId)}">View ${esc(x.category)} →</a></div></li>`).join("")||'<li class="empty">Recent updates will appear here after content is saved.</li>'}
function renderExperience(items){$("#experienceList").innerHTML=byOrder(items).map(x=>`<article id="item-${esc(x.id)}" class="experience-card"><div class="experience-date">${esc(dateLabel(x.date)||"Start date")}${x.current?" — Present":x.endDate?` — ${esc(dateLabel(x.endDate))}`:""}</div><div class="experience-main"><header><div><p class="company">${esc(x.company)} · ${esc(x.workMode||x.location||x.type||"")}</p><h3>${esc(x.role)}</h3></div>${x.current?'<span class="status">CURRENT</span>':""}</header>${x.details?.length?`<ul class="detail-list">${x.details.map(d=>`<li>${esc(d)}</li>`).join("")}</ul>`:""}${tags(x.skills||[])}${x.links?.length?`<div class="card-links">${links(x.links)}</div>`:""}</div></article>`).join("")||'<p class="empty">Experience will appear here.</p>'}
function renderProjects(){const q=$("#projectSearch").value.toLowerCase();const list=state.projects.filter(x=>(state.filter==="All"||(x.tags||[]).includes(state.filter))&&JSON.stringify(x).toLowerCase().includes(q));$("#projectGrid").innerHTML=list.map((x,i)=>`<article id="item-${esc(x.id)}" class="project-card" data-project-id="${esc(x.id)}" tabindex="0" role="button" aria-label="View ${esc(x.name)} details">${x.image?`<div class="project-image-link"><img src="${esc(x.image)}" alt="${esc(x.name)}"></div>`:""}<div class="project-body"><span class="project-no">${String(i+1).padStart(2,"0")} ${x.featured?"· FEATURED":""}</span><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p>${tags((x.tags||[]).slice(0,5))}<div class="card-links"><button type="button" data-open-project="${esc(x.id)}">View details →</button>${x.repo?`<a href="${esc(x.repo)}" target="_blank">GitHub ↗</a>`:""}${x.demo?`<a href="${esc(x.demo)}" target="_blank">Live demo ↗</a>`:""}</div></div></article>`).join("")||'<p class="empty">No matching projects.</p>';$("#projectGrid").querySelectorAll("[data-project-id]").forEach(card=>{const open=()=>openProject(card.dataset.projectId);card.onclick=e=>{if(!e.target.closest("a"))open()};card.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open()}}})}
function openProject(id){const x=state.projects.find(item=>item.id===id);if(!x)return;const d=$("#projectDialog");$("#projectDialogContent").innerHTML=`<article class="modal-project"><div class="modal-project-visual">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.name)} project image">`:'<div class="project-image-empty">SD</div>'}</div><div class="modal-project-copy"><p class="section-index">PROJECT CASE FILE ${x.status?`/ ${esc(x.status)}`:""}</p><h2 id="projectDialogTitle">${esc(x.name)}</h2>${x.date?`<time datetime="${esc(x.date)}">${esc(dateLabel(x.date))}</time>`:""}<p class="project-lead">${esc(x.description)}</p>${x.details?`<div class="project-long-copy">${esc(x.details).replace(/\n/g,"<br>")}</div>`:""}<section class="project-stack"><h3>Technology stack</h3>${tags(x.tags||[])}</section><div class="project-detail-actions">${x.repo?`<a href="${esc(x.repo)}" target="_blank" rel="noreferrer">View on GitHub ↗</a>`:""}${x.demo?`<a class="primary" href="${esc(x.demo)}" target="_blank" rel="noreferrer">Open live project ↗</a>`:""}</div></div></article>`;d.showModal()}
function setupProjectDialog(){const d=$("#projectDialog");$("#projectClose").onclick=()=>d.close();d.onclick=e=>{if(e.target===d)d.close()}}
function setupFilters(projects){const counts={};projects.flatMap(x=>x.tags||[]).forEach(x=>counts[x]=(counts[x]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,6).map(x=>x[0]);$("#projectFilters").innerHTML=["All",...top].map(x=>`<button class="${x==="All"?"active":""}" data-filter="${esc(x)}">${esc(x)}</button>`).join("");$("#projectFilters").onclick=e=>{const b=e.target.closest("button");if(!b)return;state.filter=b.dataset.filter;$("#projectFilters").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));renderProjects()};$("#projectSearch").oninput=renderProjects}
function renderPublications(items){$("#publicationList").innerHTML=byOrder(items).map(x=>`<article id="item-${esc(x.id)}" class="research-card"><div class="year">${esc(x.year||dateLabel(x.date))}</div><div><h3>${esc(x.title)}</h3><p>${esc(x.authors)}${x.notes?` · ${esc(x.notes)}`:""}</p><div class="card-links">${x.doi?`<a href="https://doi.org/${esc(x.doi.replace(/^https?:\/\/(?:dx\.)?doi\.org\//,""))}" target="_blank">DOI ↗</a>`:""}${x.paperUrl?`<a href="${esc(x.paperUrl)}" target="_blank">Paper ↗</a>`:""}${x.codeUrl?`<a href="${esc(x.codeUrl)}" target="_blank">Code ↗</a>`:""}</div></div><div class="research-state">${esc(x.venue)}</div></article>`).join("")||'<p class="empty">Research will appear here.</p>'}
function renderEducation(items){$("#educationList").innerHTML=byOrder(items).map(x=>`<article id="item-${esc(x.id)}" class="education-card"><h3>${esc(x.degree)}</h3><p>${esc(x.school)}${x.location?` · ${esc(x.location)}`:""}</p><p>${esc(dateLabel(x.date))}${x.endDate?` — ${esc(dateLabel(x.endDate))}`:""}${x.cgpa?` · CGPA ${esc(x.cgpa)}`:x.gpa?` · GPA ${esc(x.gpa)}`:""}</p>${x.details?.length?`<p>${esc(x.details.filter(d=>!/^C?GPA:/i.test(d)).join(" · "))}</p>`:""}</article>`).join("")}
function renderCredentials(items){$("#credentialGrid").innerHTML=byOrder(items).map(x=>`<article id="item-${esc(x.id)}" class="credential-card">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.title)} certificate">`:""}<div class="credential-body"><h3>${esc(x.title)}</h3><p>${esc(x.issuer)} · ${esc(dateLabel(x.issueDate))}${x.credentialId?` · ID ${esc(x.credentialId)}`:""}</p>${x.credentialUrl?`<a href="${esc(x.credentialUrl)}" target="_blank">Verify credential ↗</a>`:""}</div></article>`).join("")}
const socialIcons={github:"github",codeforce:"codeforces","code force":"codeforces",codeforces:"codeforces",linkedin:"linkedin","google scholar":"googlescholar",researchgate:"researchgate",orcid:"orcid"};
function renderHome(home){$("#heroName").textContent=home.name;$("#heroTitle").textContent=home.title;$("#heroAbout").textContent=home.about;$("#profileImage").src=home.profileImage;$("#currentFocusText").textContent=home.currentFocus||"Useful systems, trustworthy AI";const contact=home.contact||{},wanted=new Set(["github","linkedin"]),mainLinks=(home.links||[]).filter(x=>wanted.has(x.label.toLowerCase())).slice(0,2);$("#heroLinks").innerHTML=links(mainLinks)+`${contact.email?`<a href="mailto:${esc(contact.email)}">Email ↗</a>`:""}<a href="#cv">View CV →</a>`;$("#primaryContacts").innerHTML=contact.email?`<a href="mailto:${esc(contact.email)}"><span>Email</span>${esc(contact.email)}</a>`:"";$("#importantLinks").innerHTML=(home.links||[]).filter(x=>x.url).map(x=>{const key=x.label.toLowerCase(),slug=socialIcons[key],icon=key==="linkedin"?'<span class="linkedin-mark" aria-hidden="true">in</span>':slug?`<img src="https://cdn.simpleicons.org/${slug}/10233F" alt="${esc(x.label)} logo" loading="lazy">`:esc(x.label.slice(0,2));return `<a href="${esc(x.url)}" target="_blank" rel="noreferrer" title="${esc(x.label)}"><b>${icon}</b><span>${esc(x.label)}</span></a>`}).join("");const cvs=[{title:"Industry-focused CV",text:"Backend engineering, software systems and applied development.",url:home.industryCvPdf||home.resumePdf},{title:"Academic-focused CV",text:"Research, publications, academic work and technical study.",url:home.academicCvPdf}];$("#cvGrid").innerHTML=cvs.map((x,i)=>`<article class="cv-card"><span>0${i+1}</span><h3>${x.title}</h3><p>${x.text}</p>${x.url?`<div><a href="${esc(x.url)}" target="_blank">Open CV ↗</a><a href="${esc(x.url)}" download>Download ↓</a></div>`:'<em>Upload this CV from the admin panel.</em>'}</article>`).join("")}
function renderCurrentRole(items){const x=byOrder(items).find(item=>item.current)||byOrder(items)[0];$("#currentRole").innerHTML=x?`<span><i></i> CURRENTLY</span><div><strong>${esc(x.role)}</strong><small>${esc(x.company)}${x.workMode?` · ${esc(x.workMode)}`:""}</small></div>`:""}
function showPage(){const id=location.hash.slice(1)||"overview";const target=document.getElementById(id)||$("#overview");document.body.dataset.page=target.id;document.querySelectorAll(".page-section").forEach(x=>x.classList.toggle("active",x===target));document.querySelectorAll(".rail nav a").forEach(a=>a.classList.toggle("active",a.hash===`#${target.id}`));window.scrollTo(0,0);document.title=`${target.id[0].toUpperCase()+target.id.slice(1)} — Saikat Das`}
function setupNewsLinks(){$("#newsList").addEventListener("click",e=>{const a=e.target.closest("[data-focus]");if(!a)return;const id=a.dataset.focus;setTimeout(()=>{const item=document.getElementById(`item-${id}`);if(item){item.scrollIntoView({behavior:"smooth",block:"center"});item.classList.add("focused-item");setTimeout(()=>item.classList.remove("focused-item"),1800)}},80)})}
function localAnswer(q){const text=q.toLowerCase();const all=[...state.projects,...state.publications,...state.experience,...state.education];const matches=all.filter(x=>JSON.stringify(x).toLowerCase().includes(text)||text.split(/\s+/).filter(w=>w.length>3).some(w=>JSON.stringify(x).toLowerCase().includes(w))).slice(0,3);if(matches.length)return matches.map(x=>`${x.name||x.title||x.role||x.degree}: ${x.description||x.notes||(x.details||[]).join(" ")||x.company||x.school}`).join("\n\n");if(/skill|technology|tech/.test(text))return `Saikat’s listed skills include ${(state.home.skills||[]).slice(0,12).join(", ")}.`;if(/who|about|saikat/.test(text))return state.home.about;return "I could not find that in Saikat’s published portfolio. Try asking about a project name, research, experience, skills or education."}
function bubble(text,who){const el=document.createElement("div");el.className=`chat-bubble ${who}`;el.textContent=text;$("#chatMessages").appendChild(el);$("#chatMessages").scrollTop=$("#chatMessages").scrollHeight;return el}
async function askChat(q){if(state.chatBusy)return;state.chatBusy=true;$("#chatSend").disabled=true;$("#chatSuggestions").hidden=true;const pending=bubble("Thinking…","bot");pending.classList.add("thinking");try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:q,history:state.chatHistory.slice(-6)})});if(!r.ok)throw new Error();const data=await r.json();pending.textContent=data.answer;state.chatHistory.push({role:"user",content:q},{role:"assistant",content:data.answer});state.chatHistory=state.chatHistory.slice(-8)}catch{const answer=localAnswer(q);pending.textContent=answer;state.chatHistory.push({role:"user",content:q},{role:"assistant",content:answer})}finally{pending.classList.remove("thinking");state.chatBusy=false;$("#chatSend").disabled=false;$("#chatInput").focus()}}
function setupChat(){const d=$("#chatDialog"),submit=q=>{q=String(q||"").trim();if(!q||state.chatBusy)return;bubble(q,"user");$("#chatInput").value="";askChat(q)},open=()=>{d.showModal();setTimeout(()=>$("#chatInput").focus(),80)};$("#chatOpen").onclick=open;$("#footerChat").onclick=open;$("#chatClose").onclick=()=>d.close();$("#chatForm").onsubmit=e=>{e.preventDefault();submit($("#chatInput").value)};$("#chatSuggestions").onclick=e=>{const button=e.target.closest("button");if(button)submit(button.textContent)}}
function setupMobileNav(){const button=$("#menuToggle"),rail=document.querySelector(".rail");button.onclick=()=>{const open=rail.classList.toggle("nav-open");button.setAttribute("aria-expanded",String(open))};$("#siteNav").onclick=e=>{if(e.target.closest("a")){rail.classList.remove("nav-open");button.setAttribute("aria-expanded","false")}}}
async function init(){try{const [home,projects,experience,publications,education,licences,news]=await Promise.all([json("home"),json("projects"),json("experience"),json("publications"),json("education"),json("licences"),json("news")]);Object.assign(state,{home,projects:byOrder(projects),experience,publications,education});renderHome(home);renderCurrentRole(experience);renderNews(news);renderExperience(experience);setupFilters(projects);renderProjects();renderPublications(publications);renderEducation(education);renderCredentials(licences);$("#projectCount").textContent=projects.length;$("#publicationCount").textContent=publications.length;$("#credentialCount").textContent=licences.length;$("#skillCount").textContent=home.skills?.length||0;$("#year").textContent=new Date().getFullYear();setupChat();setupProjectDialog();setupMobileNav();setupNewsLinks();showPage();addEventListener("hashchange",showPage)}catch(e){document.body.innerHTML=`<p class="empty">${esc(e.message)}. Run this site through a local server.</p>`}}
init();
